"use client";
import { useEffect, useRef, useState } from "react";
import type { CmsDocument } from "@/lib/cms";
import type { Article } from "@/lib/articles";
type Content = Record<string, unknown>;
const pictures = ["kitchen","floor","windows","bathroom","equipment","interior","hall-after"].map(n=>`/images/editorial/${n}.jpg`);
export default function CmsEditor() {
  const [docs,setDocs]=useState<CmsDocument[]>([]),[selected,setSelected]=useState<CmsDocument|null>(null),[content,setContent]=useState<Content>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false);
  const lock=useRef(false);
  useEffect(()=>{let active=true;fetch("/api/crm/content").then(async r=>{const d=await r.json() as {error?:string;documents:CmsDocument[]};if(!r.ok)throw new Error(d.error);if(active)setDocs(d.documents);}).catch(e=>{if(active)setMessage(e.message||"Не удалось загрузить материалы");});return()=>{active=false;};},[]);
  useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard);},[dirty,busy]);
  function open(doc:CmsDocument){if(dirty&&!window.confirm("Открыть другой материал? Несохранённые правки будут потеряны."))return;setSelected(doc);setContent(JSON.parse(doc.draft));setDirty(false);setPreview(false);setMessage("");}
  function change(key:string,value:unknown){setContent(c=>({...c,[key]:value}));setDirty(true);}
  function create(){if(dirty&&!window.confirm("Создать статью без сохранения текущих правок?"))return;const date=new Date().toISOString().slice(0,10);const data={slug:"",title:"",seoTitle:"",description:"",excerpt:"",category:"Советы по уборке",readTime:"3 минуты",publishedAt:date,modifiedAt:date,image:pictures[0],sections:[{heading:"",paragraphs:[""],bullets:[]}],relatedServices:[]};setSelected({id:"article:",kind:"article",draft:JSON.stringify(data),published:null,previous:null,version:0,updated_at:""});setContent(data);setDirty(false);setPreview(false);}
  async function save(action:string){
    if(!selected||lock.current)return;
    if(action!=="save"&&!window.confirm(action==="publish"?"Опубликовать изменения на сайте?":action==="hide"?"Убрать статью из публичного раздела? Сохранённый текст останется в CMS.":"Вернуть предыдущую опубликованную версию?"))return;
    lock.current=true;setBusy(true);setMessage("");
    try{const slug=selected.id==="article:"?String(content.slug):selected.id.split(":")[1];const response=await fetch("/api/crm/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:selected.kind,slug,content,version:selected.version,action})});const result=await response.json() as {error?:string;documents:CmsDocument[]};if(!response.ok)throw new Error(result.error);setDocs(result.documents);const doc=result.documents.find((d:CmsDocument)=>d.id===`${selected.kind}:${slug}`);if(!doc)throw new Error("Сохранено, но список не обновился");setSelected(doc);setContent(JSON.parse(doc.draft));setDirty(false);setMessage(action==="save"?"Черновик сохранён. Сайт не изменён.":"Изменения опубликованы.");}catch(e){setMessage(e instanceof Error?e.message:"Нет связи. Ваши правки остаются здесь.");}finally{lock.current=false;setBusy(false);}
  }
  function field(key:string,label:string,multi=false){return <label key={key}>{label}{multi?<textarea rows={3} value={String(content[key]??"")} onChange={e=>change(key,e.target.value)}/>:<input value={String(content[key]??"")} onChange={e=>change(key,e.target.value)}/>}</label>;}
  const sections=(content.sections||[]) as Article["sections"];
  return <div className="cms-layout"><aside className="desk-card cms-list"><button className="desk-primary" onClick={create} disabled={busy}>+ Написать статью</button>{["service","article"].map(kind=><section key={kind}><h3>{kind==="service"?"Страницы услуг":"Статьи"}</h3>{docs.filter(d=>d.kind===kind).map(d=><button key={d.id} className={selected?.id===d.id?"selected":""} onClick={()=>open(d)} disabled={busy}><b>{JSON.parse(d.draft).title||JSON.parse(d.draft).name}</b><small>{d.published&&d.published!=="null"?"На сайте":"Не опубликовано"}{d.draft!==d.published?" · есть черновик":""}</small></button>)}</section>)}</aside><section className="desk-card cms-editor">
    {message&&<p role="status" className="desk-message">{message}</p>}
    {!selected?<div className="desk-empty"><h2>Сайт под вашим контролем</h2><p>Выберите услугу или статью слева. Сохраняйте правки в черновик, проверяйте и публикуйте отдельно.</p></div>:<>
      <div className="desk-section-title"><div><h2>{selected.kind==="article"?"Редактор статьи":"Страница услуги"}</h2><small role="status">{busy?"Сохраняем изменения…":dirty?"Есть несохранённые правки":selected.id==="article:"?"Новая статья — ещё не сохранена":"Все правки сохранены"}</small></div><button onClick={()=>setPreview(!preview)}>{preview?"Редактировать":"Предпросмотр"}</button></div>
      {preview?<article className="cms-preview"><h1>{String(content.title||content.name||"")}</h1><p>{String(content.excerpt||content.description||"")}</p>{sections.map((s,i)=><section key={i}><h2>{s.heading}</h2>{s.paragraphs.map((p,j)=><p key={j}>{p}</p>)}<ul>{s.bullets?.map((p,j)=><li key={j}>{p}</li>)}</ul></section>)}{selected.kind==="service"&&<><p>{String(content.price)} · {String(content.duration)}</p><h3>Что входит</h3><ul>{(content.includes as string[]).map((p,i)=><li key={i}>{p}</li>)}</ul></>}</article>:<fieldset className="cms-fields cms-edit-lock" disabled={busy} aria-label="Содержимое материала" aria-busy={busy}>
        {selected.kind==="article"?<>
          {selected.id==="article:"?field("slug","Адрес статьи (латиницей, через дефис)"):<p className="desk-muted">Адрес: /articles/{selected.id.split(":")[1]}</p>}
          {field("title","Заголовок")}{field("excerpt","Краткое описание для карточки",true)}
          <div className="desk-form-grid">{field("category","Рубрика")}{field("readTime","Время чтения")}{field("publishedAt","Дата публикации (ГГГГ-ММ-ДД)")}</div>
          <details><summary>Настройки поиска (SEO)</summary>{field("seoTitle","Заголовок в поиске")}{field("description","Описание в поиске",true)}</details>
          {sections.map((s,i)=><fieldset key={i}><legend>Раздел {i+1}</legend><label>Подзаголовок<input value={s.heading} onChange={e=>change("sections",sections.map((v,j)=>j===i?{...v,heading:e.target.value}:v))}/></label><label>Текст — абзацы разделяйте пустой строкой<textarea rows={7} value={s.paragraphs.join("\n\n")} onChange={e=>change("sections",sections.map((v,j)=>j===i?{...v,paragraphs:e.target.value.split("\n\n")}:v))}/></label><label>Список — каждый пункт с новой строки<textarea value={s.bullets?.join("\n")||""} onChange={e=>change("sections",sections.map((v,j)=>j===i?{...v,bullets:e.target.value.split("\n").filter(Boolean)}:v))}/></label><button disabled={sections.length<2} onClick={()=>change("sections",sections.filter((_,j)=>j!==i))}>Убрать раздел</button></fieldset>)}
          <button onClick={()=>change("sections",[...sections,{heading:"",paragraphs:[""],bullets:[]}])}>+ Раздел статьи</button>
        </>:<>{field("name","Название услуги")}{field("eyebrow","Короткая подпись")}{field("description","Описание",true)}<div className="desk-form-grid">{field("price","Цена для страницы")}{field("duration","Продолжительность")}</div><p className="desk-muted">Цены калькулятора меняются отдельно в разделе «Тарифы».</p>{["includes","notIncluded"].map(key=><label key={key}>{key==="includes"?"Входит в услугу":"Согласовывается отдельно"}<textarea rows={6} value={(content[key] as string[]||[]).join("\n")} onChange={e=>change(key,e.target.value.split("\n").filter(Boolean))}/></label>)}</>}
        <label>Изображение<select value={String(content.image||"")} onChange={e=>change("image",e.target.value)}><option value="">Без изображения</option>{[...new Set([...pictures,String(content.image||"")])].filter(Boolean).map(p=><option value={p} key={p}>{p.split("/").pop()}</option>)}</select></label>
      </fieldset>}
      <div className="cms-actions"><button disabled={busy} onClick={()=>save("save")}>Сохранить черновик</button><button disabled={busy} className="desk-primary" onClick={()=>save("publish")}>Опубликовать</button>{selected.kind==="article"&&selected.published&&selected.published!=="null"&&<button disabled={busy} onClick={()=>save("hide")}>Снять с публикации</button>}{selected.previous&&<button disabled={busy} onClick={()=>save("restore")}>Вернуть прошлую версию</button>}</div>
    </>}
  </section></div>;
}
