"use client";
import { FormEvent, ReactNode, useEffect, useRef, useState } from "react";
import { matchesCrmSearch, overdueOrder, unfinished } from "@/lib/crm-display";
import type { WorkspaceData, CrmOrder, CrmLead } from "@/lib/crm-data";
import { orderStatuses, leadStatuses } from "@/lib/crm-validation";
import CmsEditor from "./CmsEditor";
import { extrasCatalog, type ExtraKey } from "@/lib/quote";
import BrandLogo from "./BrandLogo";
import DeliveryStatus from "./DeliveryStatus";

const services:Record<string,string>={regular:"Поддерживающая",deep:"Генеральная",renovation:"После ремонта",office:"Офис / бизнес"};
const money=(n:number)=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(n);
const stamp=(s:string)=>new Date(s).toLocaleString("ru-RU",{timeZone:"Asia/Novosibirsk",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});
function Field({label,name,value="",type="text",required=false}:{label:string;name:string;value?:string|number;type?:string;required?:boolean}){return <label>{label}<input name={name} type={type} defaultValue={value} required={required} min={type==="number"?0:undefined} maxLength={type==="text"?500:undefined}/></label>;}
function Select({label,name,value,items}:{label:string;name:string;value:string;items:Record<string,string>}){return <label>{label}<select name={name} defaultValue={value}>{Object.entries(items).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;}
function Empty({children}:{children:ReactNode}){return <div className="desk-empty">{children}</div>;}
export default function CrmWorkspace({initial,user,today,notifications}:{initial:WorkspaceData;user:{name:string;role:string;signOut:string};today:string;notifications:boolean}){
  const [data,setData]=useState(initial),[tab,setTab]=useState("orders"),[query,setQuery]=useState(""),[filter,setFilter]=useState("active"),[order,setOrder]=useState<CrmOrder|null>(null),[lead,setLead]=useState<CrmLead|null>(null),[create,setCreate]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[customer,setCustomer]=useState<string|null>(null);
  const lock=useRef(false),intakeId=useRef("");
  const [dirty,setDirty]=useState(false);
  const hasCard=!!(order||lead||create);
  useEffect(()=>{if(!hasCard||!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[hasCard,dirty]);
  useEffect(()=>{if(!hasCard)return;const onInput=(e:Event)=>{if((e.target as Element).closest(".desk-drawer"))setDirty(true);};document.addEventListener("input",onInput);document.addEventListener("change",onInput);return()=>{document.removeEventListener("input",onInput);document.removeEventListener("change",onInput);};},[hasCard]);
  async function refresh(){const r=await fetch("/api/crm/workspace",{cache:"no-store"});const d=await r.json() as WorkspaceData & {error?:string};if(!r.ok)throw new Error(d.error||"Не удалось обновить данные");setData(d);}
  async function mutate(url:string,method:string,payload:unknown,done?:()=>void){if(lock.current)return;lock.current=true;setBusy(true);setNotice("");try{const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Не удалось сохранить");setDirty(false);done?.();setNotice("Сохранено");try{await refresh();}catch{setNotice("Сохранено. Обновить список не удалось — нажмите «Обновить».");}}catch(e){setNotice(e instanceof Error?e.message:"Нет связи. Попробуйте ещё раз.");}finally{lock.current=false;setBusy(false);}}
  function form(event:FormEvent<HTMLFormElement>){event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget));}
  function close(){if(busy)return;if(!dirty||window.confirm("Закрыть карточку? Несохранённые изменения будут потеряны.")){setOrder(null);setLead(null);setCreate(false);setDirty(false);}}
  const matched=(value:string)=>matchesCrmSearch(value,query);
  const visible=data.orders.filter(o=>matched(`${o.name} ${o.phone} ${o.order_number} ${o.address}`)&&(filter==="all"||(filter==="active"?unfinished(o.status):o.status===filter)));
  const overdue=data.orders.filter(o=>overdueOrder(o,today));
  const activeLeads=data.leads.filter(l=>l.status!=="closed");
  const completed=data.orders.filter(o=>o.status==="completed");
  const costs=completed.reduce((s,o)=>s+o.cleaner_cost+o.supplies_cost+o.acquisition_cost+o.other_cost,0);
  const revenue=data.orders.filter(o=>o.status==="completed").reduce((s,o)=>s+(o.final_total??o.estimate_total),0);
  const unpaid=data.orders.filter(o=>o.status==="completed"&&o.payment_status!=="paid");
  const nav={orders:"Заказы",leads:`Обращения${activeLeads.length?` · ${activeLeads.length}`:""}`,schedule:"Расписание",clients:"Клиенты",team:"Команда",finance:"Финансы",pricing:"Тарифы",...(user.role==="owner"?{content:"Сайт и статьи"}:{})};
  const clients=new Map<string,{name:string;phone:string;orders:CrmOrder[]}>();
  for(const item of [...data.orders,...data.leads]){const phone=item.phone.replace(/\D/g,"").replace(/^8/,"7");if(!clients.has(phone))clients.set(phone,{name:item.name,phone:item.phone,orders:[]});if("order_number"in item)clients.get(phone)!.orders.push(item);}
  function table(orders:CrmOrder[]){return <div className="desk-table"><table><thead><tr><th>Клиент / заказ</th><th>Уборка</th><th>Когда</th><th>Статус</th><th>Стоимость</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><button className="desk-link" onClick={()=>setOrder(o)}>{o.name}</button><small>{o.order_number} · {o.phone}</small></td><td>{services[o.service_type]}<small>{o.area} м² · {o.city}</small></td><td>{o.preferred_date||"Не назначено"}<small>{o.preferred_slot||""}</small></td><td><span className={`desk-status ${o.status}`}>{orderStatuses[o.status as keyof typeof orderStatuses]||o.status}</span><small>{o.payment_status==="paid"?"Оплачено":o.payment_status==="partial"?"Частично оплачено":"Не оплачено"}</small></td><td>{money(o.final_total??o.estimate_total)}</td></tr>)}</tbody></table>{!orders.length&&<Empty>Заказов по этому фильтру нет.</Empty>}</div>;}
  return <div className="desk"><aside className="desk-sidebar"><a href="/" aria-label="Открыть сайт"><BrandLogo /></a><p className="desk-muted">Рабочий кабинет</p><nav aria-label="Разделы кабинета">{Object.entries(nav).map(([id,title])=><button key={id} aria-current={tab===id?"page":undefined} onClick={()=>{if(tab==="content"&&!window.confirm("Перейти в другой раздел? Сначала сохраните правки CMS."))return;setTab(id);setQuery("");setCustomer(null);}}>{title}</button>)}</nav><div className="desk-account"><b>{user.name}</b><small>{user.role==="owner"?"Владелец":"Менеджер"}</small><a href={user.signOut}>Выйти</a></div></aside><main className="desk-main">
    <header className="desk-header"><div><p className="desk-muted">БлескПРО / управление</p><h1>{nav[tab as keyof typeof nav]}</h1></div><div className="desk-actions"><a href="/" target="_blank" rel="noreferrer">Открыть сайт</a><button disabled={busy} onClick={()=>{setBusy(true);refresh().then(()=>setNotice("Данные обновлены")).catch(e=>setNotice(e.message)).finally(()=>setBusy(false));}}>Обновить</button><button className="desk-primary" onClick={()=>{intakeId.current=crypto.randomUUID();setCreate(true);}}>+ Обращение</button></div></header>
    {notice&&<div className="desk-message" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Закрыть уведомление">×</button></div>}
    {!notifications&&<div className="desk-warning">Уведомления менеджеру ещё не подключены. Публичные формы не принимают заявку без канала доставки; в кабинете можно добавлять обращения вручную.</div>}
    {tab==="orders"&&<><section className="desk-metrics"><article><span>Новых заказов</span><b>{data.orders.filter(o=>o.status==="new").length}</b></article><article><span>На сегодня</span><b>{data.orders.filter(o=>o.preferred_date===today&&o.status!=="cancelled").length}</b></article><article><span>Завершённые работы</span><b>{money(revenue)}</b></article><article><span>Ожидают оплаты</span><b>{unpaid.length}</b></article></section><div className="desk-toolbar"><input aria-label="Поиск заказов" placeholder="Имя, телефон, адрес или номер" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Статус заказов" value={filter} onChange={e=>setFilter(e.target.value)}>{Object.entries({active:"Все активные",all:"Все заказы",...orderStatuses}).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div><section className="desk-card">{table(visible)}</section><p className="desk-muted">Последние 500 заказов. Финансы рассчитаны по этой выборке; сумма завершённых работ — не подтверждение поступления денег.</p></>}
    {tab==="leads"&&<section className="desk-card"><div className="desk-section-title"><h2>Сначала свяжитесь с клиентом</h2><input aria-label="Поиск обращений" placeholder="Имя или телефон" value={query} onChange={e=>setQuery(e.target.value)}/></div>{data.leads.filter(l=>matched(`${l.name} ${l.phone}`)).map(l=><div className="desk-lead" key={l.id}><div><button className="desk-link" onClick={()=>setLead(l)}>{l.name}</button><a href={`tel:${l.phone.replace(/[^+\d]/g,"")}`}>{l.phone}</a></div><p>{l.notes||"Без комментария"}</p><span className="desk-status">{leadStatuses[l.status as keyof typeof leadStatuses]||l.status}</span><small>{stamp(l.created_at)}</small></div>)}{!data.leads.length&&<Empty>Новых обращений пока нет. Здесь появятся заявки на звонок и обращения, добавленные вручную.</Empty>}</section>}
    {tab==="schedule"&&<section className="desk-card">{overdue.length>0&&<section className="desk-day"><h2>Требуют внимания · {overdue.length}</h2><p className="desk-warning">Дата уборки уже прошла. Уточните результат или перенесите заказ — незавершённые работы остаются здесь.</p>{table(overdue)}</section>}<div className="desk-section-title"><h2>Ближайшие работы</h2><p>Время — Новосибирск</p></div>{[...new Set(data.orders.filter(o=>o.preferred_date&&o.preferred_date>=today&&unfinished(o.status)).map(o=>o.preferred_date!))].sort().map(date=><section className="desk-day" key={date}><h3>{date}</h3>{table(data.orders.filter(o=>o.preferred_date===date&&unfinished(o.status)))}</section>)}{!data.orders.some(o=>o.preferred_date&&o.preferred_date>=today&&unfinished(o.status))&&<Empty>Предстоящих работ с назначенной датой пока нет.</Empty>}<h3>Нужно назначить дату</h3>{table(data.orders.filter(o=>!o.preferred_date&&unfinished(o.status)))}</section>}
    {tab==="clients"&&<section className="desk-card"><div className="desk-section-title"><h2>История по телефону клиента</h2><input aria-label="Поиск клиентов" placeholder="Имя или телефон" value={query} onChange={e=>setQuery(e.target.value)}/></div>{[...clients.entries()].filter(([,c])=>matched(`${c.name} ${c.phone}`)).map(([key,c])=><div className="desk-customer" key={key}><button className="desk-link" onClick={()=>setCustomer(customer===key?null:key)}>{c.name} · {c.phone}</button><span>{c.orders.length} заказов · {money(c.orders.filter(o=>o.status==="completed").reduce((s,o)=>s+(o.final_total??o.estimate_total),0))}</span>{customer===key&&table(c.orders)}</div>)}{!clients.size&&<Empty>Клиенты появятся после первого обращения.</Empty>}</section>}
    {tab==="team"&&<><section className="desk-team">{data.crews.map(c=><article className="desk-card" key={c.id}><h2>{c.name}</h2><a href={`tel:${c.phone||""}`}>{c.phone||"Телефон не указан"}</a><p>{c.capacity_hours} ч/день</p><small>Активных заказов: {data.orders.filter(o=>o.assigned_crew_id===c.id&&!["completed","cancelled"].includes(o.status)).length}</small><details><summary>Изменить исполнителя</summary><form className="desk-form" onSubmit={e=>{const p=form(e);mutate(`/api/crm/crews/${c.id}`,"PATCH",p);}}><Field label="Имя" name="name" value={c.name} required/><Field label="Телефон" name="phone" value={c.phone||""}/><Field label="Часов в день" name="capacityHours" type="number" value={c.capacity_hours}/><Select label="Доступность" name="status" value={c.status} items={{active:"Работает",inactive:"Не работает"}}/><button disabled={busy}>Сохранить</button></form></details></article>)}</section><form className="desk-card desk-form" onSubmit={e=>{const f=e.currentTarget;const p=form(e);mutate("/api/crm/crews","POST",p,()=>f.reset());}}><h2>Добавить исполнителя</h2><div className="desk-form-grid"><Field label="Имя или бригада" name="name" required/><Field label="Телефон" name="phone" type="tel"/><Field label="Часов в день" name="capacityHours" type="number" value={8}/></div><button className="desk-primary" disabled={busy}>Добавить</button></form></>}
    {tab==="finance"&&<section className="desk-card"><h2>Экономика завершённых работ</h2><p>Последние 500 заказов. Только внесённые затраты, без налогов и постоянных расходов.</p><div className="desk-metrics"><article><span>Стоимость работ</span><b>{money(revenue)}</b></article><article><span>Внесённые расходы</span><b>{money(costs)}</b></article><article><span>Вклад после расходов</span><b>{money(revenue-costs)}</b></article><article><span>Средний чек</span><b>{money(completed.length?revenue/completed.length:0)}</b></article></div><h3>Завершены, но не полностью оплачены</h3>{table(unpaid)}</section>}
    {tab==="pricing"&&<form key={JSON.stringify(data.pricing)} className="desk-card desk-form" onSubmit={e=>{const p=form(e);mutate("/api/crm/pricing","PATCH",{rules:data.pricing.map(r=>({key:r.key,rate:Number(p[`${r.key}-rate`]),minimum:Number(p[`${r.key}-minimum`])}))});}}><h2>Цены калькулятора</h2><p>Новые цены применятся к новым расчётам. Сохранённые заказы не пересчитываются.</p><div className="desk-team">{data.pricing.map(r=><fieldset key={r.key}><legend>{r.label}</legend><Field label="За м², ₽" name={`${r.key}-rate`} type="number" value={r.rate}/><Field label="Минимальная стоимость, ₽" name={`${r.key}-minimum`} type="number" value={r.minimum}/></fieldset>)}</div><button className="desk-primary" disabled={busy}>Сохранить тарифы</button></form>}
    {tab==="content"&&user.role==="owner"&&<CmsEditor/>}
  </main>
  {(order||lead||create)&&<div className="desk-overlay"><section className="desk-drawer" role="dialog" aria-modal="true" aria-label={order?"Карточка заказа":lead?"Карточка обращения":"Новое обращение"} onKeyDown={e=>{if(e.key==="Escape")close();if(e.key==="Tab"){const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><button className="desk-close" autoFocus onClick={close} disabled={busy} aria-label="Закрыть карточку">×</button>
    {notice&&<p className="desk-message" role="status">{notice}</p>}
    {(order||lead)&&<DeliveryStatus items={data.deliveries.filter(item=>order ? item.order_id===order.id||item.lead_id===order.lead_id : item.lead_id===lead!.id)}/>}
    {create&&<form className="desk-form" onSubmit={e=>{const p=form(e);mutate("/api/crm/leads","POST",{...p,id:intakeId.current,consent:p.consent==="on"},()=>setCreate(false));}}><h2>Новое обращение</h2><p>Добавьте контакт. Детали уборки можно согласовать позже.</p><Field label="Имя" name="name" required/><Field label="Телефон" name="phone" type="tel" required/><Select label="Город" name="city" value="Новосибирск" items={{Новосибирск:"Новосибирск",Бердск:"Бердск"}}/><Select label="Откуда клиент" name="source" value="direct" items={{direct:"Звонок / напрямую",referral:"Рекомендация",maps:"Карты",ads:"Реклама"}}/><label>Комментарий<textarea name="notes" rows={4}/></label><label className="desk-check"><input type="checkbox" name="consent" required/>Согласие клиента на обработку контактов получено</label><button className="desk-primary" disabled={busy}>Сохранить обращение</button></form>}
    {order&&<form key={order.id} className="desk-form" onSubmit={e=>{const p=form(e);mutate(`/api/crm/orders/${order.id}`,"PATCH",{...p,version:order.updated_at},()=>setOrder(null));}}><p className="desk-muted">{order.order_number}</p><h2>{order.name}</h2><a href={`tel:${order.phone.replace(/[^+\d]/g,"")}`}>{order.phone}</a><p>{services[order.service_type]} · {order.area} м² · расчёт {money(order.estimate_total)}</p><p className="desk-note">{order.notes}</p><p>{order.crew_size} чел. · ориентир {order.duration_hours} ч.</p><p>Дополнительно: {(() => {try {const list=JSON.parse(order.extras_json||"[]") as string[];return list.map(k=>extrasCatalog[k as ExtraKey]?.label||k).join(", ")||"Нет";}catch{return "Уточнить";}})()}</p><div className="desk-form-grid"><Select label="Статус" name="status" value={order.status} items={orderStatuses}/><Select label="Оплата" name="paymentStatus" value={order.payment_status} items={{unpaid:"Не оплачено",partial:"Частично",paid:"Оплачено"}}/><Field label="Дата уборки" name="date" type="date" value={order.preferred_date||""}/><Field label="Время / интервал" name="slot" value={order.preferred_slot||""}/></div><Field label="Адрес" name="address" value={order.address||""}/><Select label="Исполнитель" name="crew" value={order.assigned_crew_id||""} items={{"":"Не назначен",...Object.fromEntries(data.crews.filter(c=>c.status==="active").map(c=>[c.id,c.name]))}}/><Field label="Согласованная стоимость, ₽ (пусто — расчёт)" name="finalTotal" type="number" value={order.final_total??""}/><details><summary>Расходы по заказу</summary><div className="desk-form-grid"><Field label="Исполнители, ₽" name="cleanerCost" type="number" value={order.cleaner_cost}/><Field label="Средства, ₽" name="suppliesCost" type="number" value={order.supplies_cost}/><Field label="Привлечение, ₽" name="acquisitionCost" type="number" value={order.acquisition_cost}/><Field label="Прочее, ₽" name="otherCost" type="number" value={order.other_cost}/></div></details><label>Добавить комментарий<textarea name="note" rows={3}/></label><button className="desk-primary" disabled={busy}>Сохранить заказ</button><h3>Файлы клиента</h3>{data.files.filter(f=>f.order_id===order.id).map(f=><a key={f.id} href={`/api/crm/files/${f.id}`} target="_blank" rel="noreferrer">{f.file_name}</a>)}<h3>История</h3>{data.activities.filter(a=>a.order_id===order.id).map(a=><p key={a.id}><small>{stamp(a.created_at)}</small><br/>{a.body}</p>)}</form>}
    {lead&&<><form key={lead.id} className="desk-form" onSubmit={e=>{const p=form(e);mutate(`/api/crm/leads/${lead.id}`,"PATCH",{...p,version:lead.updated_at},()=>setLead(null));}}><h2>{lead.name}</h2><a href={`tel:${lead.phone.replace(/[^+\d]/g,"")}`}>{lead.phone}</a><Select label="Статус общения" name="status" value={lead.status} items={leadStatuses}/><label>Заметки<textarea name="notes" rows={5} defaultValue={lead.notes||""}/></label><button className="desk-primary" disabled={busy}>Сохранить обращение</button></form><details className="desk-convert"><summary>Клиент согласен — создать заказ</summary><form className="desk-form" onSubmit={e=>{const p=form(e);mutate(`/api/crm/leads/${lead.id}`,"POST",p,()=>setLead(null));}}><Select label="Вид уборки" name="service" value="regular" items={services}/><Field label="Площадь, м²" name="area" type="number" required/><Field label="Согласованная цена, ₽" name="total" type="number" required/><Field label="Дата" name="date" type="date"/><Field label="Адрес" name="address"/><button className="desk-primary" disabled={busy}>Создать заказ</button></form></details><h3>История обращения</h3>{data.activities.filter(a=>a.lead_id===lead.id).map(a=><p key={a.id}><small>{stamp(a.created_at)}</small><br/>{a.body}</p>)}</>}
  </section></div>}
  </div>;
}
